services:
  service-users:
    build: ./backend/users
    env_file:
      - ./backend/users/.env
    ports:
      - "3001:3000"
    restart: always
    depends_on:
      - users-db
      - redis
    networks: [backend]

  users-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: usersdb
    ports:
      - "5433:5432"
    volumes:
      - users_data:/var/lib/postgresql/data
    networks:
      - backend

  service-activity:
    build: ./backend/activity
    env_file:
      - ./backend/activity/.env
    ports:
      - "3002:3000"
    restart: always
    environment:
      USERS_API: http://service-users:3000
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./backend/activity/uploads:/usr/src/app/uploads
    depends_on:
      - activity-db
      - redis
    networks: [backend]

  activity-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: activitydb
    ports:
      - "5434:5432"
    volumes:
      - activity_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    networks: [backend]

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend/activity/uploads:/usr/src/app/uploads
    ports:
      - "8080:8080"
    depends_on:
      - service-users
      - service-activity
    networks: [backend]

volumes:
  users_data:
  activity_data:

networks:
  backend:
    driver: bridge
